# Generated by Django 5.2 on 2025-04-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merk', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('harga_dasar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pinjaman_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suku_bunga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_service', models.DateField()),
                ('deskripsi', models.TextField()),
                ('biaya_service', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mobil.mobil')),
            ],
        ),
    ]
