# Generated by Django 5.2 on 2025-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='menggunakan_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga_dasar',
            field=models.IntegerField(),
        ),
    ]
